// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

// Load .env.local and override existing process.env variables (to avoid conflicts with .env)
config({ path: path.resolve(process.cwd(), ".env.local"), override: true });

let dbUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "";

// Prisma 7 and URL parsing: The password "Immi2026h20#*" contains a '#', 
// which must be encoded as "%23" to avoid parsing errors (P1013).
if (dbUrl.includes('#') && !dbUrl.includes('%23')) {
  // Simple replacement for the password part. 
  // A more robust way is to use the URL object, but it fails if the URL is invalid.
  dbUrl = dbUrl.replace('#', '%23');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
